### ISSUE TITLE
Change Hotkey?

### ISSUE THREAD

**Issue by brutus** [antonfisher/flap-app-launcher#1]
Is there any way to change the default hotkey? 

Preferably to just the `super` key instead of `super+space`?

**Comment by antonfisher** [comment]
Hey, nice to see the first issue!
Currently, the only way is to change the source code: https://github.com/antonfisher/flap-app-launcher/blob/master/index.js#L11
I'm going to add settings file+window soon.
Customizable hotkeys/colors/size are planned.

**Comment by brutus** [comment]
Thanks for the response. The launcher is way faster than unity, I use it as my default for the last couple of days :smile: I found the file you mentioned in my installation (npm global) here: 

`/usr/lib/node_modules/flap-app-launcher/index.js`

When I change the default hotkey to just `super`, it is displayed in the log correctly, but seems to raise a `TypeError`:

```
> flap-app-launcher@1.0.2 start /usr/lib/node_modules/flap-app-launcher
> electron .

info: Application logs file "/home/brutus/.flap-app-launcher.log"
info: Start application
info: HotKey binding: Super
info: Statistics loaded from file "/home/brutus/.flap-app-launcher.stats"
info: Total applications found: 306
info: Error: TypeError: Error processing argument at index 0, conversion failure from Super
```

The launcher starts and I can type in it, but when pressing enter nothing happens. And I also can't "close" the launcher with the escape–key. I'm not fluent in JavaScript and never used Electron, but I think, the `TypeError` originates because the Electron library needs a Hotkey (_Accelerator_) to consist of an optional modifier __and__ another "normal" key:

https://github.com/electron/electron/blob/master/docs/api/accelerator.md

So it seems that using only `Super`is not possible?

**Comment by antonfisher** [comment]
Ha, good catch!
I'm on the same page. When I tried to change the hotkey to `Super`, I faced the same problem as you..
I need to dig into this issue, but so far this restriction looks disappointing.
BTW I just pushed configuration file support (haven't updated NPM package yet, will do tomorrow with docs).

**Comment by antonfisher** [comment]
I use it as my default app launcher too :) Before I was using this one: http://do.cooperteam.net/, for me it was faster than Unity, by I like to have the more simple interface.

**Comment by antonfisher** [comment]
New release has been issued: [v1.0.4](https://github.com/antonfisher/flap-app-launcher/releases/tag/v1.0.4)

The config file will be created after first updated application run.
To change default hotkey edit the config file:
```
# for npm or binaries installation:
vim ~/.flap-app-launcher.config.json

# for source code installation:
vim %SOURCE_DIR%/.flap-app-launcher.config.json
```
Unfortunately, single hotkeys (like just `Super`) cannot be used now due to some restrictions in Electron.
The default hotkey is `Super+Space`.

Thank you!
